version: "3"
services:
  jenkins:
    container_name: jenkins
    image: "jenkins/jenkins:lts"
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    networks:
      testingNet:
        ipv4_address: 172.18.1.10
    ports:
    - 8080:8080
networks:
  testingNet:
      ipam:
        driver: default
        config:
          - subnet: 172.18.1.0/24