version: '3.1'
services:
  jenkins:
    container_name: jenkins
    ports:
    - '8080:8080'
    - '50000:50000'
    image: "jenkins/jenkins:lts"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
    - ./jenkins:/home/jenkins # Avoid mysql volume mount issue
    networks:
      testingNet:
        ipv4_address: 172.18.1.10
networks:
  testingNet:
    ipam:
      driver: default
      config:
      - subnet: 172.18.1.0/24