version: "3"
services:
  jenkins:
    container_name: jenkins
    image: "jenkins/jenkins:lts"
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins:/var/jenkins_home
    networks:
      testingNet:
        ipv4_address: 172.18.1.10
    ports:
    - 8080:8080
  jenkins-slave:
    container_name: jenkins-slave
    restart: always
    image: "jenkins/jnlp-slave"
    environment:
      JENKINS_URL: "http://172.18.1.10:8080"
      JENKINS_SECRET: "d09c6790e1c88a81f11f2fb7b56ac8141fd8b1331da8c6bc70c352873cb5efc2"
      JENKINS_AGENT_NAME: "DockerNode"
      JENKINS_AGENT_WORKDIR: "C://Users//subkrish2//jenkinsSlave"
      JENKINS_OPTS: "-Dhudson.remoting.Launcher.pingIntervalSec=-1"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
    - ./jenkinsSlave:/var/jenkins_home/slave # Avoid mysql volume mount issue
    depends_on:
    - jenkins
    networks:
      testingNet:
        ipv4_address: 172.18.1.6
networks:
  testingNet:
      ipam:
        driver: default
        config:
          - subnet: 172.18.1.0/24